language: cpp

compiler:
  - gcc
  # - clang
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python-numpy
      - openmpi-bin
      - libopenmpi-dev
env:
  global:
    - LOCAL_INSTALL="$HOME/local"
    - CPLUS_INCLUDE_PATH="$LOCAL_INSTALL/include"
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LOCAL_INSTALL/lib"
    - LIBRARY_PATH="$LIBRARY_PATH:$LOCAL_INSTALL/lib"

  matrix:
    - MPI=off
    - MPI=on

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - mkdir -p $LOCAL_INSTALL/include $LOCAL_INSTALL/lib
  - wget http://bitbucket.org/eigen/eigen/get/3.2.5.tar.bz2 -O - | tar xj -C $LOCAL_INSTALL/include --strip-components=1 eigen-eigen-bdd17ee3b1b3/Eigen
  - wget 'http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2' -O - | tar xj
  - cd boost_1_59_0
  - export BOOST_SRC=`pwd`
  - ./bootstrap.sh
  - ./b2 --with-program_options --with-test --with-filesystem --with-log
  - ln -s "$BOOST_SRC/boost" $LOCAL_INSTALL/include/
  - ln -s "$BOOST_SRC/stage/lib/"* $LOCAL_INSTALL/lib/

before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - cd $TRAVIS_BUILD_DIR
  - scons -j 2 petsc=off mpi=$MPI python=on compiler=$CXX
  - cd tests
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  
after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat ./tests/unit-test-output
  - cat ./tests/integration-test-output
