language: cpp
dist: trusty
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - python-numpy

env:
  global:
    - LOCAL_INSTALL="$HOME/local"
    - CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:$LOCAL_INSTALL/include"
    - LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LOCAL_INSTALL/lib"
    - LIBRARY_PATH="$LIBRARY_PATH:$LOCAL_INSTALL/lib"
    - PYTHONPATH="/usr/lib/python2.7:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/plat-x86_64-linux-gnu"
    
  matrix:
    - MPI=off
    - MPI=on

cache:
  directories:
    - $LOCAL_INSTALL

before_install:
  - export OMPI_CXX=$CXX
  - if [ "$MPI" = "on" ]; then export CXX="mpicxx"; fi

install:
  - $TRAVIS_BUILD_DIR/tools/travis-install-dependencies.sh $LOCAL_INSTALL
  
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tests

script:
  - cd $TRAVIS_BUILD_DIR
  - scons -j 2 petsc=off mpi=$MPI python=on compiler=$CXX
  - cd tests
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "off" ]; then ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  - if [ "$MPI" = "off" ]; then ../build/last/testprecice -x -r detailed > boost-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-test-config.xml ../src > unit-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 ../build/last/binprecice test ../.ci-integration-test-config.xml ../src > integration-test-output; fi
  - if [ "$MPI" = "on"  ]; then mpirun.openmpi -n 4 --output-filename boost-test-output  ../build/last/testprecice -r detailed; fi
  
after_failure:
  - cd $TRAVIS_BUILD_DIR
  - cat config.log
  - cat -n ./tests/unit-test-output
  - cat -n ./tests/integration-test-output
  - cat -n ./tests/boost-test-output*


