language: cpp
compiler:
  - g++
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libboost-filesystem-dev
      - libboost-system-dev

script:
  - scons boost_inst=on petsc=off mpi=off python=off compiler=g++-4.8
  
after_failure:
  - cat config.log